modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="custom_back"
version="dev1"
displayName="Custom_Background"
displayURL=""
credits=""
authors="Biddimc"

[[custom_back]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.8.9]"
    ordering="NONE"
    side="BOTH"




